---
- name: Shutdown controller nodes
  hosts: controllers
  gather_facts: false
  tasks:
    - name: Get node names
      ansible.builtin.uri:
        url: "http://turing/api/bmc/?opt=get&type=nodeinfo"
        method: POST
      register: nodenames
      delegate_to: localhost
      tags:
        - controllers
        - setup
        - poweroff
    - name: Show node info per inventory_hostname
      ansible.builtin.debug:
        msg: "{{ item }} is {{ nodenames.json.response[0][item] }}"
        verbosity: 1
      when: 'inventory_hostname in nodenames.json.response[0][item]'
      with_items: "{{ nodenames.json.response[0] }}"
      tags:
        - controllers
        - setup
    - name: Set turing node name per inventory_hostname
      ansible.builtin.set_fact:
        tpinode: "{{ item }}"
      when: 'inventory_hostname in nodenames.json.response[0][item]'
      with_items: "{{ nodenames.json.response[0] }}"
      tags:
        - controllers
        - setup
        - poweroff
    - name: Shutdown
      community.general.shutdown:
        delay: 10
      tags:
        - controllers
        - shutdown
    - name: Wait for ping loss
      ansible.builtin.command: ping -c 2 "{{ inventory_hostname }}"
      delegate_to: localhost
      changed_when: false
      check_mode: false
      retries: 5
      until: ('100% packet loss' in pingresponse.stdout)
      failed_when: ('100% packet loss' not in pingresponse.stdout)
      register: pingresponse
      tags:
        - controllers
        - wait
        - poweroff
    - name: Show url to call
      ansible.builtin.debug:
        msg: "http://turing/api/bmc/?opt=set&type=power&{{ tpinode }}=0"
        verbosity: 1
      delegate_to: localhost
      tags:
        - controllers
        - setup
        - poweroff
    - name: Wait additional 30 seconds before power off
      ansible.builtin.wait_for:
        timeout: 30
      delegate_to: localhost
    - name: Power off node
      ansible.builtin.uri:
        url: "http://turing/api/bmc/?opt=set&type=power&{{ tpinode }}=0"
        method: POST
      delegate_to: localhost
      tags:
        - controllers
        - poweroff
